spring:
  application:
    name: spring_boot_jdbc_13
  datasource:
    url: jdbc:h2:file:~/trainDb   
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: ALWAYS
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 5050
logging:
  level:
    org:
      h2: trace
      springframework:
        jdbc: trace
